version: '2'
services:
  broker1: 
    image: quotes:0.1.3
    container_name: broker1
    ports:
      - "19011:22"
    volumes:
        - /lib64:/lib64
    volumes:
        - /mnt/Quotes:/mnt/Quotes
    command: /bin/bash
    tty: true
    restart: always
  broker2: 
    image: quotes:0.1.3
    container_name: broker2
    depends_on:
      - broker1
    ports:
      - "19012:22"  
    volumes:
        - /lib64:/lib64
    volumes:
        - /mnt/Quotes:/mnt/Quotes
    tty: true
    restart: always
  broker3: 
    image: quotes:0.1.3
    container_name: broker3
    depends_on:
      - broker2
    ports:
      - "19013:22"
    volumes:
        - /lib64:/lib64
    volumes:
        - /mnt/Quotes:/mnt/Quotes
    tty: true
    restart: always
  producer: 
    image: quotes:0.1.3
    container_name: producer
    links: 
      - broker1:hostb1
      - broker2:hostb2
      - broker3:hostb3
    ports:
      - "19014:22"
    volumes:
        - /mnt/Quotes:/mnt/Quotes
    tty: true
    restart: always
  consumer1: 
    image: quotes:0.1.3
    container_name: consumer1
    depends_on:
      - producer
    links: 
      - broker1:hostb1
      - broker2:hostb2
      - broker3:hostb3
    ports:
      - "19015:22"
    tty: true
    restart: always
  consumer2: 
    image: quotes:0.1.3
    container_name: consumer2
    depends_on:
      - consumer1
    ports:
      - "19016:22"
    links: 
      - broker1:hostb1
      - broker2:hostb2
      - broker3:hostb3
    tty: true
    restart: always
